### ISSUE TITLE
运行python example 会报错

### ISSUE THREAD

**Issue by chen-98** [yngzMiao/protobuf-parser-tool#1]
Traceback (most recent call last):
  File "D:\Files\tool_dev\toolDev\data_format\protobuf-parser-tool-master\protobuf-parser-tool-master\python\example_person.py", line 44, in <module>
    reader = PersonRead.GeneralProtoReader(protofile, GeneralProto.Person)
  File "D:\Files\tool_dev\toolDev\data_format\protobuf-parser-tool-master\protobuf-parser-tool-master\python\proto_buf\General_buf_read.py", line 21, in __init__
    self.version = self.parseBindata(self.protofile.read(4))
  File "D:\Files\tool_dev\toolDev\data_format\protobuf-parser-tool-master\protobuf-parser-tool-master\python\proto_buf\General_buf_read.py", line 87, in parseBindata
    binval = [int(struct.unpack('b', temp_len[0])[0]),
TypeError: a bytes-like object is required, not 'int'

Process finished with exit code 1

**Comment by yngzMiao** [comment]
您的邮件已经收到，我会尽快查看处理的，谢谢！ This is an automatic reply, confirming that your e-mail was received. Thank you!

**Comment by aawuliliaa** [comment]
python2,不能用python3，我测通了

**Comment by yngzMiao** [comment]
您的邮件已经收到，我会尽快查看处理的，谢谢！ This is an automatic reply, confirming that your e-mail was received. Thank you!
